---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    ms: '{{ ms }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u smuheebpasha@gmail.com -p Muheeb@123 muheeb.jfrog.io  
    
    - name: pull an image
      shell: docker pull muheeb.jfrog.io/docker-cicd-docker-local/app-a/Login:{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 muheeb.jfrog.io/docker-cicd-docker-local/app-a/Login:{{ build_number }}
 
   
